### ISSUE TITLE
Alternate Background Colour Not Working for Row/Column Until Resize?

### ISSUE THREAD

**Issue by dm-p** [dm-p/powerbi-visuals-smlc#10]
This feature was working while packaging but seems to not be working as intended - and requires a resize to apply correctly. The only one that works is by Small Multiple. We'll need to investigate and fix accordingly.

**Comment by dm-p** [comment]
Can't seem to reproduce this now that I'm looking at it after existing 2.1.0 changes. Will continue to monitor but can be closed for now.

**Comment by dm-p** [comment]
Had a DM about this on Twitter, so re-opening for further investigation

**Comment by cmajka** [comment]
The issue seems to correct itself after closing and reopening the desktop file. However, the issue reappears once I start toggling the Y axis on or off. Further, it appears that toggling different fields in the Format pane affect the alternate background in different ways. Also noted that making selections in drop down slicers in the service also appear to affect the alternate background. Reset to default appears to return the alternate background to its desired state.

**Comment by dm-p** [comment]
I've caught up with @cmajka and it looks like this has been resolved in the refactoring done in 2.1.0 (as this has gone live since intial discovery).
