### ISSUE TITLE
[ENHANCEMENT] Add Area Colour Fill

### ISSUE THREAD

**Issue by steve257** [dm-p/powerbi-visuals-smlc#2]
Ability to add area colour fill option under line

Display Option: No colour fill, Colour Fill

Eg:
https://zebrabi.com/wp-content/uploads/2019/06/Small-multiples-in-Zebra-BI.png

**Comment by dm-p** [comment]
Pretty sure we can squeeze this one in to 2.0.0. I'll take a look.

**Comment by dm-p** [comment]
I've added properties to manage area in build **2.0.0.117**.

* Measures now have a **Show Area** toggle.
* If this is set, an option to adjust **Transparency** will be available.
* Additionally, the **Stroke Width** for each measure can now be set to **0**, so that the line can be omitted from the area plot, if the author so wishes.

### Property Pane example:
![image](https://user-images.githubusercontent.com/10572054/71040013-775cdf00-218a-11ea-9382-c48306fe50ce.png)

### Resulting Visual:
![image](https://user-images.githubusercontent.com/10572054/71040058-93608080-218a-11ea-9378-faae43a2423e.png)

@steve257: please confirm if this is as you expect and I'll ensure it's in the next test version for you to have a look at.

**Comment by dm-p** [comment]
Resolved in 2.0.0.117
