### ISSUE TITLE
[SEVERE] Tooltip doesn't resolve nearest data point correctly if (Blank) or 0

### ISSUE THREAD

**Issue by LiBerti13** [dm-p/powerbi-visuals-smlc#23]
I'm using the "Auto" report page tooltip, and I have 3 measures (A, B, C) on the SMLC visual, thus also 3 measures on the tooltip. On the X axis I have dates (Day 1, 2 ,3). On Day 1 and Day 3, all 3 measures have some value which are shown on both the visual and the tooltip. On Day 2, however, only measures A and B have some value (measure C value is NULL). Both are shown on the visual, and there is no value shown for measure C, as expected. However, on the tooltip for Day 2 there *is* a value shown for measure C, which is either the value of C on Day 1 or Day 3, depending on which day I hover closer to.

This happens in both Power BI Desktop and Service (with Edge) under 64-bit Windows 10 Enterprise with SMLC version 2.1.0.130.

**Comment by LiBerti13** [comment]
Addendum: when the measure with the missing value (i.e. C in the example above) is the first measure to be plotted (i.e. the first measure in the "Values" field) then the tooltip for Day 2 is not showing up at all.
Besides, when the value of C exists but it is zero, then the tooltip is shown, but C is not shown on the tooltip, and the X axis value (normally on top of the tooltip) is not shown either. The zero value is shown on the visual itself, so that part is OK.

**Comment by dm-p** [comment]
Cheers for this - I'll have to carve out some time to investigate but I suspect I know where to find this one if it's doing what I suspect it's doing when we try to find the nearest data point to the cursor.

Just out of curiosity, do you have this already replicated in a shareable workbook? If so, are you able to email to me (daniel@coacervo.co)? I'll certainly make the diagnosis process (and verification) more straighforward.

**Comment by LiBerti13** [comment]
Hi @dm-p! I've sent you an email with an example pbix. I hope it will be a quick fix ;-)

**Comment by dm-p** [comment]
For the initial part of the issue, Root cause is that I'd originally designed `null` values to be excluded from tooltips completely. In hindsight this is terrible design, as it means the nearest data point to the mouse just keeps going, resulting in this weirdness (from @LiBerti13's example):

![image](https://user-images.githubusercontent.com/10572054/88853178-6f4a3f00-d243-11ea-87c4-269fe057c57f.png)

This will look as follows in the next build:

![image](https://user-images.githubusercontent.com/10572054/88853333-ac163600-d243-11ea-9113-90245d07a7d9.png)

To summarise:

* Resolved `null` values will show in the tooltip as `(Blank)`.
* The marker for resolved `null` values will be hidden.

----

For the second part of the issue, if that measure was placed first, then the handler would get confused trying to resolve the correct value, e.g.:

![issue_23_ii](https://user-images.githubusercontent.com/10572054/88854096-ecc27f00-d244-11ea-9d22-032a26461049.gif)

Fortunately(?) the root cause is similar to part (i), so this will work as follows in the next build:

![issue_23_ii_fix](https://user-images.githubusercontent.com/10572054/88854305-3317de00-d245-11ea-8912-40523483a5e1.gif)

----

For the third part of the issue, `0` values were misbehaving in a similar way, e.g.:

![issue_23_iii](https://user-images.githubusercontent.com/10572054/88854582-9dc91980-d245-11ea-9586-121ec5d656cc.gif)

These will now be picked-up correctly, e.g.:

![issue_23_iii_fix](https://user-images.githubusercontent.com/10572054/88854794-f26c9480-d245-11ea-91e8-0ab2b4b89931.gif)

**Comment by LiBerti13** [comment]
Awesome! This seems to fix all three issues/parts. Love the anigifs, BTW :-D
