### ISSUE TITLE
[ENHANCEMENT] Extra tooltip values

### ISSUE THREAD

**Issue by LiBerti13** [dm-p/powerbi-visuals-smlc#24]
Please consider adding a "Tooltips" field to SMLC (just like e.g. on the built-in line chart) so that one can add extra measures to be displayed on the default tooltip without displaying it on the visual itself. This can be very useful to show e.g. a text value. I know that one can create a custom report page with whatever measures to be used as a tooltip, but that is quite cumbersome, doesn't look very elegant, and rather slow.

**Comment by dm-p** [comment]
Thanks very much for your interest @LiBerti13 :)

Adding a tooltip role should be fairly straightforward - I'll try to accomodate in a future release.

**Comment by LiBerti13** [comment]
Many thanks! I'm glad to hear that it's relatively easy. Just one more thing: I'm not sure if it requires any extra effort, but it would be awesome to have not only numeric but also text values as tooltip measure (with the usual first/last/count aggregation).

**Comment by dm-p** [comment]
From build 2.2.0.133, the visual will expose a **Tooltips** data role, allowing a maximum of 5 measures or aggregations:

![image](https://user-images.githubusercontent.com/10572054/88867169-c8749b80-d260-11ea-84de-eee36085ef09.png)

Any measures or columns will be aggregated for the current Small Multiple / Axis context, e.g.:

![image](https://user-images.githubusercontent.com/10572054/88867058-8186a600-d260-11ea-8806-25222953ba33.png)

Note that because tooltips are bound to context, each additional measure added to this data role will increase the number of data points queried from model and can potentially exhaust resources if the resulting query is too complex.
