### ISSUE TITLE
[BUG] Linear Axes Starting at 0 Are not Rendered

### ISSUE THREAD

**Issue by krysta-gh** [dm-p/powerbi-visuals-smlc#6]
SMLC that were working with the previous version don't render. See attached zip file with 'png_water_use_annual.csv' (multiple = wmb, axis = year, value = any other field) that does render and 'stream_crossing_density.csv' (multiple = unit, axis = year) that doesn't render. No idea what the difference between the 2 is or why the second one stopped working. Any help would be greatly appreciated.

[csv.zip](https://github.com/dm-p/powerbi-visuals-smlc/files/4234942/csv.zip)

**Comment by krysta-gh** [comment]
Update: playing around with the format of my input files - I found a fix. The x-axis field (year in my case) has to be a text type.

**Comment by dm-p** [comment]
Hi @krysta-gh, and thanks for making me aware of this. Sorry that you're experiencing issues.

I've investigated and this is indeed a bug with how we validate the data fields going into the visual and it in the second case, your `year` field starts at zero and the visual code is treating this as 'field not added'. Not great.

This can be worked around, as you pointed out by changing the field to text (which is undesirable), or by setting the filter on the visual to start greater than `0`, e.g.:

![image](https://user-images.githubusercontent.com/10572054/75070706-ab70c980-5558-11ea-86df-1ae3d2210a96.png)

If you want to get really creative, you could do a replace in your query to set zero values for `year` to a very small non-zero number, such as `0.0001`, e.g.:

![image](https://user-images.githubusercontent.com/10572054/75071003-4ff30b80-5559-11ea-8670-85c49fa1ec50.png)

You can then set your number format on the `year` column so that it still shows as `0` in the tooltip, e.g.:
![image](https://user-images.githubusercontent.com/10572054/75071079-77e26f00-5559-11ea-90ea-54b59f077c46.png)

[Here's a workbook with my investigations if you want to take a look at these workarounds](https://github.com/dm-p/powerbi-visuals-smlc/files/4238001/Issue.6.Investigations.zip).

I'll schedule this to fix in the main visual ASAP. I can provide you with a hotfix though if this is urgent? Please note that updating the core visual takes a number of weeks to reach the marketplace, so a hotfix can be manually loaded into Power BI but will be "seen" as a different visual entirely by Power BI to the one from the marketplace.

Thanks,

Daniel

**Comment by krysta-gh** [comment]
Hi Daniel,

Thanks for the quick reply. I will use the workaround that you suggested filtering for zero and replacing year=0 with a very small number.

Thanks!

Krysta

________________________________

**Comment by dm-p** [comment]
Thanks, Krysta - I'll add the fix to the visual code and it'll be included in the next release. I don't have an ETA at present, as I'm just waiting to see if there are any further fixes pending from the certification request I have in at present.

Glad the workaround will help you out in the meantime, but if you do need me to provide a hotfix in the interim, please don't hesitate to ask and I can arrange.

**Comment by dm-p** [comment]
The correct code has been included in 2.1.0. I'm still working on a number of other issues so no ETA on when this will be generally available as yet, but the next submitted update to the marketplace will contain this fix.

**Comment by dm-p** [comment]
2.1.0 has gone live in the marketplace, so this issue is now resolved for all users :)
